name: cargo
version: master
summary: The Rust package manager
description: |
  Cargo downloads your Rust project’s dependencies and compiles your project.

grade: devel
confinement: strict

apps:
  cargo:
    command: cargo
    plugs: [home, network]

parts:
  cargo:
    source: .
    plugin: rust
